### ISSUE TITLE
Force close when loading ROMs.

### ISSUE THREAD

**Issue by MlgmXyysd** [chenxiaolong/DualBootPatcher#1113]
Device: Huawei Honor 4X (China Mobile) CHE-TL00H
Android Version: Marshmallow
logs:
05-18 09:48:20.864: E/AndroidRuntime(15285):  Process: com.github.chenxiaolong.dualbootpatcher.snapshot, PID: 15285
05-18 09:48:20.864: E/AndroidRuntime(15285):  	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.getBootPartition(SwitcherUtils.kt:78)
05-18 09:48:20.864: E/AndroidRuntime(15285):  	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.copyBootPartition(SwitcherUtils.kt:248)
05-18 09:48:20.864: E/AndroidRuntime(15285):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:64)
05-18 09:48:20.864: E/AndroidRuntime(15285):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
05-18 09:48:20.864: E/AndroidRuntime(15285):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)

**Comment by MlgmXyysd** [comment]
@chenxiaolong 
crash.log is uploaded to http://cdn.meowcat.org/mlgmxyysd/storage/20180530/crash.log
