### ISSUE TITLE
Dual Boot Patcher crash in MIUI

### ISSUE THREAD

**Issue by webmaster33** [chenxiaolong/DualBootPatcher#121]
Dual Boot Patcher crashes (r2592) in MIUI when touching any 

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1541)
	at android.app.Activity.startActivityFromFragment(Activity.java:3957)
	at android.app.Fragment.startActivityForResult(Fragment.java:1079)
	at android.app.Fragment.startActivityForResult(Fragment.java:1063)
	at com.github.chenxiaolong.dualbootpatcher.switcher.ZipFlashingFragment$1.onClick(ZipFlashingFragment.java:190)
	at android.view.View.performClick(View.java:4445)
	at android.view.View$PerformClick.run(View.java:18446)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by hankching** [comment]
The latest version is r2596.
Did you try it?

**Comment by webmaster33** [comment]
Dual Boot Patcher crashes (r2596) in MIUI V5 Samsung Galaxy S4 i9505,when touching any big + signs (file selection). 

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1541)
	at android.app.Activity.startActivityFromFragment(Activity.java:3957)
	at android.app.Fragment.startActivityForResult(Fragment.java:1079)
	at android.app.Fragment.startActivityForResult(Fragment.java:1063)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.selectInputUri(PatchFileFragment.java:697)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$200(PatchFileFragment.java:86)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$1.onClick(PatchFileFragment.java:241)
	at android.view.View.performClick(View.java:4445)
	at android.view.View$PerformClick.run(View.java:18446)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by hankching** [comment]
Can you use patch zip, go to ROM section, do any setting (for example use dark theme) or app sharing?

Do you understand what means intent?

**Comment by webmaster33** [comment]
I can't patch or flash rom, because of crash. 
Both crashes when I want to select the file. 

I turned on to allow receiving  intents, but still crashes as I wrote above.

**Comment by hankching** [comment]
Using MD5/SHA1/SHA256 file to verify your download.

**Comment by webmaster33** [comment]
APK file is a zip file. If there would be download error, would not install. 
Also this bug is present since at least r2468...

**Comment by hankching** [comment]
First, it is not zip becase zip is not for android. Android is tar/gz is most like it.

I faced checksum error when I completely full install.

**Comment by hankching** [comment]
How about r2464 and r2467?
What device do you use?

**Comment by chenxiaolong** [comment]
@webmaster33 Looks like MIUI is missing the DocumentsUI Android component. Please give the test build at #122 a try and let me know if it fixes the issue.

**Comment by webmaster33** [comment]
Better. Doesn't crash suddenly when tapping + file add sign, but later, when the file is selected in file manager. 

```
java.lang.NullPointerException
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.onQueriedMetadata(PatchFileFragment.java:830)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$2400(PatchFileFragment.java:86)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1111)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1066)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)


```

**Comment by webmaster33** [comment]
Any news about fixing this bug?

**Comment by webmaster33** [comment]
Still having the crash in Miui, when selecting the file for patch using the default file browser.

`java.lang.NullPointerException
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.onQueriedMetadata(PatchFileFragment.java:830)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment.access$2400(PatchFileFragment.java:86)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1111)
	at com.github.chenxiaolong.dualbootpatcher.patcher.PatchFileFragment$GetUriMetadataTask.onPostExecute(PatchFileFragment.java:1066)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5139)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:796)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:612)
	at dalvik.system.NativeStart.main(Native Method)
`

**Comment by chenxiaolong** [comment]
@webmaster33 Can you post a link to which MIUI ROM this is occurring on? I tried MIUI 5.1.17 (`miui_i9505_rainbow_5.7.17_e73fe591cf_4.4.zip`) and it doesn't crash.

**Comment by webmaster33** [comment]
@chenxiaolong: Your version is MIUI v6 5.7.17. My version is MIUI v5 4.9.6.
You can download from here:
http://miui-for-i9505.blogspot.hu/2014/10/rom-miui-v5-update-to-4926-stock-and.html

**Comment by chenxiaolong** [comment]
@webmaster33 Can you give the test build at #178 a try? It should fix this issue.

**Comment by webmaster33** [comment]
@chenxiaolong: You are amazing! Fixed the crash in MIUI!
Thank you very much for your support & your efforts!
