### ISSUE TITLE
Crashed on Treble Pie gsi

### ISSUE THREAD

**Issue by Trumeet** [chenxiaolong/DualBootPatcher#1291]
Device: Redmi Note 4x (mido)
ROM: Treble Pie gsi
It crashes when load rom list (starting mtool), stacktrace is attached.

![screenshot_20181013-162437](https://user-images.githubusercontent.com/17158086/46910986-d37fff80-cf04-11e8-88c0-a32f607a9f63.png)

**Comment by Trumeet** [comment]
![screenshot_20181013-163108](https://user-images.githubusercontent.com/17158086/46911016-7df82280-cf05-11e8-83e0-2ee77725cf89.png)

**Comment by Puripu** [comment]
Similar issue on Mi Mix 2s. Running Android 9.0. Latest build. Magisk installed.

Crashes every time I try to open ROMS. All other things work correctly.

a.c
at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.getBootPartition(SwitcherUtils.kt:78)
at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.copyBootPartition(SwitcherUtils.kt:248)
at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:64)
at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)

**Comment by Puripu** [comment]
Not sure if it's useful, but I've added a logcat in attachment.
[logs-2018-11-06-11-08-38.zip](https://github.com/chenxiaolong/DualBootPatcher/files/2551343/logs-2018-11-06-11-08-38.zip)

**Comment by mateHD** [comment]
Hi guys!
I have the same problem as you. Do you have solution?
MIUI 10, xiaomi.eu rom, MI8 pro and magisk.

**Comment by Trumeet** [comment]
Some weeks before I had tried the latest version and it worked correctly.

**Comment by fawzy46** [comment]
> Some weeks before I had tried the latest version and it worked correctly.

does it work on pie now? I also have Redmi Note 4x (mido)

**Comment by Trumeet** [comment]
> > Some weeks before I had tried the latest version and it worked correctly.
> 
> does it work on pie now? I also have Redmi Note 4x (mido)

I had tried it and the crash seems to be solved, but I don't believe it would work for the Treble-enabled ROMs.
The information may do not up-to-date because I had not used it for a while.
