### ISSUE TITLE
Crash on Android Pie.

### ISSUE THREAD

**Issue by MlgmXyysd** [chenxiaolong/DualBootPatcher#1330]
'''
12-17 20:41:06.489: I/ActivityManager(922):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity bnds=[540,1066][756,1376]} from uid 10049 pid 3675
12-17 20:41:06.494: E/ANDR-IOP(775):  IOP HAL: Received pkg_name = com.github.chenxiaolong.dualbootpatcher.snapshot pid = -1
12-17 20:41:06.501: D/ActivityTrigger(922):  activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot}
12-17 20:41:06.501: E/ActivityTrigger(922):  activityStartTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:06.502: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:06.502: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:06.506: D/Stats   (3675):  Intent.getPackage() is null. therefore try to get package name from componentName.getPackageName(): com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:06.512: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:06.512: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:06.512: D/RestartProcessManager(922):  Update Total Launch Times :com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:06.512: D/RestartProcessManager(922):  Package record size is abnormal in com.github.chenxiaolong.dualbootpatcher.snapshot , size : 1, max size is 30
12-17 20:41:06.512: D/RestartProcessManager(922):  updateSelf :  com.github.chenxiaolong.dualbootpatcher.snapshot, size : 30
12-17 20:41:06.512: D/RestartProcessManager(922):  Increase Total Launch Time : com.github.chenxiaolong.dualbootpatcher.snapshot, times : 1, index : 29
12-17 20:41:06.512: D/RestartProcessManager(922):  Last Running Package : com.github.chenxiaolong.dualbootpatcher.snapshot , start time 1545050466512
12-17 20:41:06.517: D/Stats   (3675):  SaveStats onPreExecute onStatsChanged:ComponentInfo{com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity}
12-17 20:41:06.530: I/ActivityManager(922):  Start proc 8578:com.github.chenxiaolong.dualbootpatcher.snapshot/u0a129 for activity com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity
12-17 20:41:06.531: I/StorageRedirectNative(4472):  process started, pid=8578 uid=10129 user=0 package=com.github.chenxiaolong.dualbootpatcher.snapshot type=activity
12-17 20:41:06.531: V/StorageRedirectNative(4472):  log: 12-17 20:41:06.530   922  1198 I am_proc_start: [0,8578,10129,com.github.chenxiaolong.dualbootpatcher.snapshot,activity,com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity]
12-17 20:41:06.535: D/GridItemProvider(3675):  saveToolBoxItemsToPreference: jsonStr= [{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.github.chenxiaolong.dualbootpatcher.MainActivity","mPackage":"com.github.chenxiaolong.dualbootpatcher.snapshot"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.github.chenxiaolong.dualbootpatcher.snapshot"},"itemType":0,"launchCount":6,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"cn.wq.myandroidtoolspro.MainActivity","mPackage":"cn.wq.myandroidtools"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"cn.wq.myandroidtools"},"itemType":0,"launchCount":6,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"rikka.appops.SplashActivity","mPackage":"rikka.appops"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"rikka.appops"},"itemType":0,"launchCount":1,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"l.ۦۦ۠ۗ","mPackage":"bin.mt.plus"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"bin.mt.plus"},"itemType":0,"launchCount":8,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.coolapk.market.view.main.MainActivity","mPackage":"com.coolapk.market"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.coolapk.market"},"itemType":0,"launchCount":18,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.thirtydegreesray.openhub.ui.activity.SplashActivity","mPackage":"com.thirtydegreesray.openhub"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.thirtydegreesray.openhub"},"itemType":0,"launchCount":1,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.tencent.mobileqq.activity.SplashActivity","mPackage":"com.tencent.mobileqq"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.tencent.mobileqq"},"itemType":0,"launchCount":25,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"eu.chainfire.liveboot.MainActivity","mPackage":"eu.chainfire.liveboot"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"eu.chainfire.liveboot"},"itemType":0,"launchCount":3,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"moe.shizuku.redirectstorage.MainActivity","mPackage":"moe.shizuku.redirectstorage"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"moe.shizuku.redirectstorage"},"itemType":0,"launchCount":3,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"a.c","mPackage":"com.topjohnwu.magisk"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"com.topjohnwu.magisk"},"itemType":0,"launchCount":11,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"mark.via.ui.activity.BrowserActivity","mPackage":"mark.via"},"mContentUserHint":-2,"mFlags":270532608,"mPackage":"mark.via"},"itemType":0,"launchCount":28,"restored":0,"serialNumber":0},{"id":0,"intent":{"mAction":"android.intent.action.MAIN","mCategories":["android.intent.category.LAUNCHER"],"mComponent":{"mClass":"com.google.android.apps.translate.TranslateActivity","mPackage":"com.google.android.apps.translate"},"mContentUser
12-17 20:41:06.540: V/StorageRedirectInject(8578):  nativeForkAndSpecialize: package=com.github.chenxiaolong.dualbootpatcher.snapshot, user=0
12-17 20:41:06.886: I/PhoneStatusBarView(2357):  isFullAndNotchEnabled() isFullMode=false pkg=com.github.chenxiaolong.dualbootpatcher.snapshot isCameraNotchIgnoreSetting=false, uid=10129
12-17 20:41:06.978: I/ActivityManager(922):  Displayed com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity: +454ms
12-17 20:41:07.140: W/SurfaceFlinger(797):  Attempting to set client state on removed layer: Splash Screen com.github.chenxiaolong.dualbootpatcher.snapshot#0
12-17 20:41:07.140: W/SurfaceFlinger(797):  Attempting to destroy on removed layer: Splash Screen com.github.chenxiaolong.dualbootpatcher.snapshot#0
12-17 20:41:07.841: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 1 line
12-17 20:41:07.974: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 6 lines
12-17 20:41:08.057: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 2 lines
12-17 20:41:08.595: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 2 lines
12-17 20:41:08.658: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 2 lines
12-17 20:41:08.810: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 4 lines
12-17 20:41:08.942: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 3 lines
12-17 20:41:09.083: D/RestartProcessManager(922):  increase duration : 2571 for com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:09.096: D/ThreadPoolService(8578):  onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService })
12-17 20:41:09.096: D/ThreadPoolService(8578):  onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=1)
12-17 20:41:09.114: D/NotificationListener(3675):  onNotificationPosted# hash: 120340908 sbn: StatusBarNotification(pkg=com.github.chenxiaolong.dualbootpatcher.snapshot user=UserHandle{0} id=1 tag=null key=0|com.github.chenxiaolong.dualbootpatcher.snapshot|1|null|10129: Notification(channel=background_service pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=service vis=PRIVATE))
12-17 20:41:09.122: D/NotificationEntryMgr(2357):  No peeking: unimportant notification: 0|com.github.chenxiaolong.dualbootpatcher.snapshot|1|null|10129
12-17 20:41:09.146: D/NotificationEntryMgr(2357):  No peeking: unimportant notification: 0|com.github.chenxiaolong.dualbootpatcher.snapshot|1|null|10129
12-17 20:41:09.147: D/NotificationEntryMgr(2357):  No peeking: unimportant notification: 0|com.github.chenxiaolong.dualbootpatcher.snapshot|1|null|10129
12-17 20:41:09.196: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:09.196: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:09.196: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:09.196: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:09.197: D/RestartProcessManager(922):  Update Total Launch Times :com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:09.197: D/RestartProcessManager(922):  updateSelf :  com.github.chenxiaolong.dualbootpatcher.snapshot, size : 30
12-17 20:41:09.197: D/RestartProcessManager(922):  Increase Total Launch Time : com.github.chenxiaolong.dualbootpatcher.snapshot, times : 2, index : 29
12-17 20:41:09.197: D/RestartProcessManager(922):  Last Running Package : com.github.chenxiaolong.dualbootpatcher.snapshot , start time 1545050469197
12-17 20:41:09.202: D/ThreadPoolService(8578):  Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask@d478a06 to thread pool: default
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:159)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.access$initConnectToSocket(MbtoolConnection.kt:108)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection.connect(MbtoolConnection.kt:61)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection.<init>(MbtoolConnection.kt:83)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:55)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:09.204: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  com.github.chenxiaolong.dualbootpatcher.socket.exceptions.MbtoolException: java.io.IOException: Connection refused
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:163)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.access$initConnectToSocket(MbtoolConnection.kt:108)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection.connect(MbtoolConnection.kt:61)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection.<init>(MbtoolConnection.kt:83)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:55)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:09.204: E/GetRomsStateTask(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:159)
12-17 20:41:09.211: I/ActivityManager(922):  START u0 {cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity (has extras)} from uid 10129 pid 8578
12-17 20:41:09.215: D/ActivityTrigger(922):  activityStartTrigger: Activity is not Triggerred in full screen ApplicationInfo{29550f5 com.github.chenxiaolong.dualbootpatcher.snapshot}
12-17 20:41:09.215: D/ActivityTrigger(922):  activityResumeTrigger: Activity is not Triggerred in full screen ApplicationInfo{29550f5 com.github.chenxiaolong.dualbootpatcher.snapshot}
12-17 20:41:09.215: D/RestartProcessManager(922):  Duration is too short, ignore : 18 in com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:09.229: D/ActivityTrigger(922):  activityResumeTrigger: Activity is not Triggerred in full screen ApplicationInfo{29550f5 com.github.chenxiaolong.dualbootpatcher.snapshot}
12-17 20:41:09.229: D/RestartProcessManager(922):  Update Total Launch Times :com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:09.229: D/RestartProcessManager(922):  updateSelf :  com.github.chenxiaolong.dualbootpatcher.snapshot, size : 30
12-17 20:41:09.229: D/RestartProcessManager(922):  Increase Total Launch Time : com.github.chenxiaolong.dualbootpatcher.snapshot, times : 2, index : 29
12-17 20:41:09.229: D/RestartProcessManager(922):  Last Running Package : com.github.chenxiaolong.dualbootpatcher.snapshot , start time 1545050469229
12-17 20:41:09.265: D/ThreadPoolService(8578):  Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.UpdateMbtoolWithRootTask@81758a8 to thread pool: default
12-17 20:41:09.265: D/ThreadPoolService(8578):  onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService }, flags=0, startId=2)
12-17 20:41:09.270: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:159)
12-17 20:41:09.270: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.replaceViaSignedExec(MbtoolConnection.kt:336)
12-17 20:41:09.270: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.UpdateMbtoolWithRootTask.execute(UpdateMbtoolWithRootTask.kt:40)
12-17 20:41:09.270: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:09.270: E/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:09.271: W/MbtoolConnection(8578):  com.github.chenxiaolong.dualbootpatcher.socket.exceptions.MbtoolException: java.io.IOException: Connection refused
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:163)
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.replaceViaSignedExec(MbtoolConnection.kt:336)
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.UpdateMbtoolWithRootTask.execute(UpdateMbtoolWithRootTask.kt:40)
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:09.271: W/MbtoolConnection(8578):  	at com.github.chenxiaolong.dualbootpatcher.socket.MbtoolConnection$Companion.initConnectToSocket(MbtoolConnection.kt:159)
12-17 20:41:09.282: I/ActivityManager(922):  Displayed com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity: +51ms (total +182ms)
12-17 20:41:09.316: D/SurfaceFlinger(797):  duplicate layer name: changing com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity to com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity#1
12-17 20:41:09.340: V/CommandUtils(8578):  Command: 'cp' '/data/user/0/com.github.chenxiaolong.dualbootpatcher.snapshot/files/data-9.3.0.r866.g9227f348/binaries/android/arm64-v8a/mbtool' '/mnt/mb_tmp/mbtool'
12-17 20:41:09.409: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 2 lines
12-17 20:41:09.476: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 1 line
12-17 20:41:09.625: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 5 lines
12-17 20:41:09.940: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 17 lines
12-17 20:41:10.090: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 7 lines
12-17 20:41:10.229: D/RestartProcessManager(922):  Duration is too short, ignore : 999 in com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:10.231: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:10.231: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:10.232: D/ActivityTrigger(922):  activityResumeTrigger: The activity in ApplicationInfo{77e4da1 com.github.chenxiaolong.dualbootpatcher.snapshot} is now in focus and seems to be in full-screen mode
12-17 20:41:10.232: E/ActivityTrigger(922):  activityResumeTrigger: not whiteListedcom.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity/1
12-17 20:41:10.232: D/RestartProcessManager(922):  Update Total Launch Times :com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:10.232: D/RestartProcessManager(922):  updateSelf :  com.github.chenxiaolong.dualbootpatcher.snapshot, size : 30
12-17 20:41:10.232: D/RestartProcessManager(922):  Increase Total Launch Time : com.github.chenxiaolong.dualbootpatcher.snapshot, times : 2, index : 29
12-17 20:41:10.232: D/RestartProcessManager(922):  Last Running Package : com.github.chenxiaolong.dualbootpatcher.snapshot , start time 1545050470232
12-17 20:41:10.241: D/ThreadPoolService(8578):  Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask@f240d7f to thread pool: default
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.RomConfig.loadFile(RomConfig.kt:154)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.RomConfig.access$loadFile(RomConfig.kt:35)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.RomConfig$Companion.getConfig(RomConfig.kt:190)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.RomUtils.loadConfig(RomUtils.kt:164)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.RomUtils.getRoms(RomUtils.kt:157)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:58)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:10.299: E/RomConfig(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:10.356: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 1 line
12-17 20:41:10.373: W/SurfaceFlinger(797):  Attempting to set client state on removed layer: com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity#1
12-17 20:41:10.373: W/SurfaceFlinger(797):  Attempting to destroy on removed layer: com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity#1
12-17 20:41:10.423: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 1 line
12-17 20:41:10.455: E/AndroidRuntime(8578):  Process: com.github.chenxiaolong.dualbootpatcher.snapshot, PID: 8578
12-17 20:41:10.455: E/AndroidRuntime(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.getBootPartition(SwitcherUtils.kt:78)
12-17 20:41:10.455: E/AndroidRuntime(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.copyBootPartition(SwitcherUtils.kt:248)
12-17 20:41:10.455: E/AndroidRuntime(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:64)
12-17 20:41:10.455: E/AndroidRuntime(8578):  	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111)
12-17 20:41:10.455: E/AndroidRuntime(8578):  	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150)
12-17 20:41:10.473: I/chatty  (8578):  uid=10129(com.github.chenxiaolong.dualbootpatcher.snapshot) RenderThread identical 1 line
12-17 20:41:10.496: W/ActivityManager(922):    Force finishing activity com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity
12-17 20:41:10.501: D/RestartProcessManager(922):  Duration is too short, ignore : 266 in com.github.chenxiaolong.dualbootpatcher.snapshot
12-17 20:41:10.514: W/InputDispatcher(922):  channel 'b18c956 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-17 20:41:10.514: E/InputDispatcher(922):  channel 'b18c956 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-17 20:41:10.519: W/InputDispatcher(922):  channel '5a69567 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-17 20:41:10.519: E/InputDispatcher(922):  channel '5a69567 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-17 20:41:10.519: I/WindowManager(922):  WIN DEATH: Window{b18c956 u0 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity}
12-17 20:41:10.519: W/InputDispatcher(922):  Attempted to unregister already unregistered input channel 'b18c956 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.socket.MbtoolErrorActivity (server)'
12-17 20:41:10.521: I/ActivityManager(922):  Process com.github.chenxiaolong.dualbootpatcher.snapshot (pid 8578) has died: vis  +99TOP 
12-17 20:41:10.522: W/ActivityManager(922):  Scheduling restart of crashed service com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherService in 20895ms
12-17 20:41:10.525: I/WindowManager(922):  WIN DEATH: Window{5a69567 u0 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity}
12-17 20:41:10.525: W/InputDispatcher(922):  Attempted to unregister already unregistered input channel '5a69567 com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity (server)'
12-17 20:41:10.528: W/SurfaceFlinger(797):  Attempting to set client state on removed layer: com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity#0
12-17 20:41:10.528: W/SurfaceFlinger(797):  Attempting to destroy on removed layer: com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity#0
12-17 20:41:10.547: D/FrequentAppsGrid(3675):  App icon adds to Shelf: ComponentInfo{com.github.chenxiaolong.dualbootpatcher.snapshot/com.github.chenxiaolong.dualbootpatcher.MainActivity}
12-17 20:41:10.550: D/NotificationListener(3675):  onNotificationRemoved# hash: 120340908 sbn: StatusBarNotification(pkg=com.github.chenxiaolong.dualbootpatcher.snapshot user=UserHandle{0} id=1 tag=null key=0|com.github.chenxiaolong.dualbootpatcher.snapshot|1|null|10129: Notification(channel=background_service pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 color=0x00000000 category=service vis=PRIVATE))
'''
Device:OnePlus 6 (A6000)
System:Android 9 (Pie,API 28)
Root: MagiskSU 18.0

App ask me to config mbtool.
After granted root access,force crash.

**Comment by chenxiaolong** [comment]
Can you try with version `9.3.0.r913.g9dcd6c6f`? I cannot reproduce the crash there.
