### ISSUE TITLE
Apk is crashing when losts focus (appears a pop up message in other app)

### ISSUE THREAD

**Issue by klorinczi** [chenxiaolong/DualBootPatcher#1393]
Apk is crashing when losts focus (appears a pop up message in other app)

Attaching crash log file. 
[crash.log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/2854536/crash.log.txt)

**Comment by chenxiaolong** [comment]
```
02-12 06:55:43.831   418   418 E AndroidRuntime: FATAL EXCEPTION: main
02-12 06:55:43.831   418   418 E AndroidRuntime: Process: com.github.chenxiaolong.dualbootpatcher.snapshot, PID: 418
02-12 06:55:43.831   418   418 E AndroidRuntime: java.lang.IllegalStateException: Already querying metadata!
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.InAppFlashingFragment.queryUriMetadata(InAppFlashingFragment.kt:429)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.InAppFlashingFragment.onServiceConnected(InAppFlashingFragment.kt:275)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1453)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1481)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6236)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
02-12 06:55:43.831   418   418 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
```
Hmm, I must not be handling the `onStop`/`onPause` correctly.

**Comment by Skyrimus** [comment]
My problem same this
