### ISSUE TITLE
Crash when opening "ROMs"

### ISSUE THREAD

**Issue by mateHD** [chenxiaolong/DualBootPatcher#1415]
/Multiboot/logs/crash.log:

`beginning of crash 03-14 10:22:23.089 14896 14940 E AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1 03-14 10:22:23.089 14896 14940 E AndroidRuntime: Process: com.github.chenxiaolong.dualbootpatcher.snapshot, PID: 14896 03-14 10:22:23.089 14896 14940 E AndroidRuntime: a.c 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.getBootPartition(SwitcherUtils.kt:78) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.SwitcherUtils.copyBootPartition(SwitcherUtils.kt:248) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.kt:64) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.kt:111) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$enqueueOperation$$inlined$synchronized$lambda$1.run(ThreadPoolService.kt:150) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 03-14 10:22:23.089 14896 14940 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764) 03-14 10:22:23.093 14896 14940 E MainApplication: Thread[pool-1-thread-1,5,main] has crashed with an uncaught exception; dumping log 03-14 10:22:23.094 14896 14940 V LogUtils: Dumping logcat: [logcat, -d, -f, /storage/emulated/0/MultiBoot/logs/crash.log, -v, threadtime, *:V] 
`

Device: MIUI 10 on Xiaomi Mi8 Pro

**Comment by mrbox24** [comment]
I got around this crash by setting my device codename to a value expected by DBP. For example I an HTC 10 US T-Mobile variant Resurrection Remix(7.0.1) ROM names the the device pme, however DBP expects htc_pmewl for device codename. The magisk module MagiskHide Props config can accomplish this. Good luck, hope this helps.

**Comment by Skyrimus** [comment]
I have the same problem on ALPS 8.1, I think this error should not be if the code name is incorrect

**Comment by Skyrimus** [comment]
> I got around this crash by setting my device codename to a value expected by DBP. For example I an HTC 10 US T-Mobile variant Resurrection Remix(7.0.1) ROM names the the device pme, however DBP expects htc_pmewl for device codename. The magisk module MagiskHide Props config can accomplish this. Good luck, hope this helps.

Bro, your solution works great! But i think this issue need be fixed

**Comment by Skyrimus** [comment]
@chenxiaolong plz fix it and crashes when flashing rom after roll up application :)
