### ISSUE TITLE
Dual Boot doesn`t modify Boot.img

### ISSUE THREAD

**Issue by cryscript** [chenxiaolong/DualBootPatcher#214]
Several times I added support for Dual boot Patcher, but this time not make everything okay.
The problem is that after installing the second ROM and boot the second ROM it does not start. It seems that the kernel from second ROM runs as it is not right and tries to start the primary ROM, even the bootanimation from the first ROM. The main ROM is working fine even with the updated ramdisk.
All the changes made by me here: https://github.com/cryscript/DualBootPatcher/commit/7ad848d9b69067a5899ed9b783c54068887a28e5
Logs : [20161001.102833.tar.gz](https://github.com/chenxiaolong/DualBootPatcher/files/504468/20161001.102833.tar.gz)
Hope you understand that i write, because English is not my first language.

**Comment by cryscript** [comment]
I found the problem. Dual boot does not modify the boot.img, but I don`t know how to fix this problem.

link to boot.img https://yadi.sk/d/_koOFt7qwFrLU

**Comment by cryscript** [comment]
I think I found problem. 
Its patch-file.log, it have many errors
```
--------- beginning of main
10-16 21:26:24.150  6621  6621 I LoadedApk: No resource references to update in package common
10-16 21:26:24.151  6621  6621 I LoadedApk: No resource references to update in package rtosta.theme.brownnice
10-16 21:26:24.151  6621  6621 I LoadedApk: No resource references to update in package com.dtaf.alonso.gux
10-16 21:26:24.233  6621  6621 D ExternalStorage: After updating volumes, found 1 active roots
10-16 21:26:24.262  6621  6635 D Documents: Update found 1 roots in 9ms
10-16 21:26:24.282  6621  6621 W art     : Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-16 21:26:24.303  6621  6621 I AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
10-16 21:26:24.342  6621  6621 W Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
10-16 21:26:24.406  6621  6642 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
10-16 21:26:24.417  6621  6621 D SwitcherService: onCreate()
10-16 21:26:24.417  6621  6621 D SwitcherService: onBind(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher/.switcher.SwitcherService })
10-16 21:26:24.418  6621  6621 D SwitcherService: onStartCommand(intent=Intent { cmp=com.github.chenxiaolong.dualbootpatcher/.switcher.SwitcherService }, flags=0, startId=1)
10-16 21:26:24.428  6621  6642 I Adreno  : QUALCOMM build                   : cababe8, I8a8f1b7e8f
10-16 21:26:24.428  6621  6642 I Adreno  : Build Date                       : 07/16/16
10-16 21:26:24.428  6621  6642 I Adreno  : OpenGL ES Shader Compiler Version: XE031.09.00.03
10-16 21:26:24.428  6621  6642 I Adreno  : Local Branch                     : 
10-16 21:26:24.428  6621  6642 I Adreno  : Remote Branch                    : 
10-16 21:26:24.428  6621  6642 I Adreno  : Remote Branch                    : 
10-16 21:26:24.428  6621  6642 I Adreno  : Reconstruct Branch               : 
10-16 21:26:24.435  6621  6642 I OpenGLRenderer: Initialized EGL, version 1.4
10-16 21:26:24.661  6621  6621 D SwitcherService: Added runnable com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask@b004067 to thread pool: default
10-16 21:26:24.682  6621  6666 E RomConfig: Failed to load /storage/emulated/0/MultiBoot/primary/config.json
10-16 21:26:24.682  6621  6666 E RomConfig: java.io.FileNotFoundException: /storage/emulated/0/MultiBoot/primary/config.json: open failed: ENOENT (No such file or directory)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at libcore.io.IoBridge.open(IoBridge.java:452)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.io.FileReader.<init>(FileReader.java:66)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.loadFile(RomConfig.java:221)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.getConfig(RomConfig.java:79)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.loadConfig(RomUtils.java:300)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.getRoms(RomUtils.java:275)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.java:71)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.java:125)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$1.run(ThreadPoolService.java:181)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at java.lang.Thread.run(Thread.java:818)
10-16 21:26:24.682  6621  6666 E RomConfig: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at libcore.io.Posix.open(Native Method)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-16 21:26:24.682  6621  6666 E RomConfig: 	at libcore.io.IoBridge.open(IoBridge.java:438)
10-16 21:26:24.682  6621  6666 E RomConfig: 	... 13 more
10-16 21:26:24.686  6621  6666 E RomConfig: Failed to load /storage/emulated/0/MultiBoot/data-slot-mi/config.json
10-16 21:26:24.686  6621  6666 E RomConfig: java.io.FileNotFoundException: /storage/emulated/0/MultiBoot/data-slot-mi/config.json: open failed: ENOENT (No such file or directory)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at libcore.io.IoBridge.open(IoBridge.java:452)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.io.FileInputStream.<init>(FileInputStream.java:103)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.io.FileReader.<init>(FileReader.java:66)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.loadFile(RomConfig.java:221)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomConfig.getConfig(RomConfig.java:79)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.loadConfig(RomUtils.java:300)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.RomUtils.getRoms(RomUtils.java:275)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.GetRomsStateTask.execute(GetRomsStateTask.java:71)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.switcher.service.BaseServiceTask.run(BaseServiceTask.java:125)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at com.github.chenxiaolong.dualbootpatcher.ThreadPoolService$1.run(ThreadPoolService.java:181)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at java.lang.Thread.run(Thread.java:818)
10-16 21:26:24.686  6621  6666 E RomConfig: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at libcore.io.Posix.open(Native Method)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-16 21:26:24.686  6621  6666 E RomConfig: 	at libcore.io.IoBridge.open(IoBridge.java:438)
10-16 21:26:24.686  6621  6666 E RomConfig: 	... 13 more
10-16 21:26:24.687  6621  6666 D RomUtils: mbtool says current ROM ID is: primary

```
**How I can fix this?**
