### ISSUE TITLE
com.android.phone force closes in secondary ROM

### ISSUE THREAD

**Issue by thewisenerd** [chenxiaolong/DualBootPatcher#44]
I am trying to bring up DualBootPatcher for ferrari (mi 4i), and am currently facing issues with the secondary ROM.

I have followed the following steps:

1. in primary ROM, patch ROM as secondary
2. flash _dual.zip for secondary ROM in recovery
3. reboot device (device boots into secondary, no FCs)
4. install .apk file, and switch to primary ROM
5. in primary ROM, switch back to secondary ROM
6. reboot from the power menu (phone boots into secondary)
7. device boots into secondary, com.android.phone FC's.

herein i attach parts of logcat which i think are relevant:

```
E/SQLiteDatabase( 1696): Failed to open database '/data/data/com.android.providers.telephony/databases/HbpcdLookup.db'.
E/SQLiteDatabase( 1696): android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
E/SQLiteDatabase( 1696): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1179)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
E/SQLiteDatabase( 1696): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
E/SQLiteDatabase( 1696): 	at com.android.providers.telephony.HbpcdLookupProvider.onCreate(HbpcdLookupProvider.java:155)
E/SQLiteDatabase( 1696): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
E/SQLiteDatabase( 1696): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1705)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5039)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4634)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
E/SQLiteDatabase( 1696): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/SQLiteDatabase( 1696): 	at android.os.Looper.loop(Looper.java:135)
E/SQLiteDatabase( 1696): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/SQLiteDatabase( 1696): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteDatabase( 1696): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/SQLiteDatabase( 1696): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/SQLiteDatabase( 1696): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/SQLiteOpenHelper( 1696): Couldn't open HbpcdLookup.db for writing (will try read-only):
E/SQLiteOpenHelper( 1696): android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
E/SQLiteOpenHelper( 1696): 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1179)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
E/SQLiteOpenHelper( 1696): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
E/SQLiteOpenHelper( 1696): 	at com.android.providers.telephony.HbpcdLookupProvider.onCreate(HbpcdLookupProvider.java:155)
E/SQLiteOpenHelper( 1696): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
E/SQLiteOpenHelper( 1696): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1705)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5039)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4634)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
E/SQLiteOpenHelper( 1696): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/SQLiteOpenHelper( 1696): 	at android.os.Looper.loop(Looper.java:135)
E/SQLiteOpenHelper( 1696): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/SQLiteOpenHelper( 1696): 	at java.lang.reflect.Method.invoke(Native Method)
E/SQLiteOpenHelper( 1696): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/SQLiteOpenHelper( 1696): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/SQLiteOpenHelper( 1696): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

```
D/AndroidRuntime( 3163): Shutting down VM
E/AndroidRuntime( 3163): FATAL EXCEPTION: main
E/AndroidRuntime( 3163): Process: com.android.phone, PID: 3163
E/AndroidRuntime( 3163): java.lang.RuntimeException: Unable to get provider com.android.providers.telephony.HbpcdLookupProvider: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5042)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4634)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4574)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
E/AndroidRuntime( 3163): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3163): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 3163): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3163): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 3163): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 3163): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 3163): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:600)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
E/AndroidRuntime( 3163): 	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:825)
E/AndroidRuntime( 3163): 	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:864)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:241)
E/AndroidRuntime( 3163): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
E/AndroidRuntime( 3163): 	at com.android.providers.telephony.HbpcdLookupProvider.onCreate(HbpcdLookupProvider.java:155)
E/AndroidRuntime( 3163): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1730)
E/AndroidRuntime( 3163): 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1705)
E/AndroidRuntime( 3163): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5039)
E/AndroidRuntime( 3163): 	... 11 more
```

entire log here: https://gist.github.com/thewisenerd/78fddbc80024a8484322

**Comment by chenxiaolong** [comment]
I've seen a very similar issue occur with TouchWiz primary ROMs before on Samsung devices. The primary ROM is likely changing the SELinux label on the other ROM's files. On my device, for example, the label for `/data/data/com.android.providers.telephony/databases/HbpcdLookup.db` from your log is `u:object_r:radio_data_file:s0 `. If the primary ROM somehow ran `restorecon` on the secondary ROM's data directory, the label would be changed to `u:object_r:system_data_file:s0`. On the next boot, com.android.phone (and many other packages) would FC.

Could you extract the boot.img and see if the following lines is in one of the `init.rc` or `init.*.rc` files?

    restorecon_recursive /data

OR

    restorecon -R /data

If so, you'll need to use the ramdisk update function from the app (equivalent to patching the primary ROM) as the multiboot code removes that line before booting Android.

**Comment by thewisenerd** [comment]
ah, yes. thanks a lot :relaxed: 

there was the said line ```restorecon /data``` in init.rc of primary ROM's boot.img, and using the "update ramdisk" function fixed it.

Issue was *bogus* and can be closed :stuck_out_tongue:
