### ISSUE TITLE
APK reboot function not working

### ISSUE THREAD

**Issue by cedricpoon** [chenxiaolong/DualBootPatcher#60]
I am currently using cm12 on hlte and this function stopped working since 8.0.0.r2157.g7d47ab8. Please take a look over this feature, thanks.

**Comment by chenxiaolong** [comment]
If you run the following command with adb, is it able to reboot your phone?

    adb shell am start --ez android.intent.extra.KEY_CONFIRM true -a android.intent.action.REBOOT

**Comment by cedricpoon** [comment]
Above adb command comes up with the following error log:

Starting: Intent { act=android.intent.action.REBOOT (has extras) }
java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.REBOOT flg=0x10000000 cmp=android/com.android.internal.app.ShutdownActivity (has extras) } from null (pid=21633, uid=2000) requires android.permission.SHUTDOWN
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.ActivityManagerProxy.startActivityAsUser(ActivityManagerNative.java:2485)
        at com.android.commands.am.Am.runStart(Am.java:766)
        at com.android.commands.am.Am.onRun(Am.java:305)
        at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
        at com.android.commands.am.Am.main(Am.java:97)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

**Comment by chenxiaolong** [comment]
Snapshot version `8.0.0.r2250.g594fc03` should fix this issue, I think. Would you mind giving it a try? Thanks.

**Comment by cedricpoon** [comment]
Sure. Could you please share to me the link to 8.0.0.r2251.gd9a452d?

**Comment by chenxiaolong** [comment]
@cedricpoon Sure, the build is available here: https://snapshots.noobdev.io/

Direct links:
Android: https://snapshots.noobdev.io/DualBootPatcherAndroid-8.0.0.r2251.gd9a452d-snapshot.apk
Win32: https://snapshots.noobdev.io/DualBootPatcher-8.0.0.r2251.gd9a452d-win32.zip
Utilities: https://snapshots.noobdev.io/DualBootUtilities-8.0.0.r2251.gd9a452d.zip

**Comment by cedricpoon** [comment]
Fixed 8.0.0.r2251.gd9a452d
