### ISSUE TITLE
Jenkins builds frequently fail due to git-plugin bug

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/DualBootPatcher#89]
We're always hitting this bug https://issues.jenkins-ci.org/browse/JENKINS-22795 on one of the build slaves. For whatever reason, Jenkins randomly refuses to use the previously cloned `DualBootPatcher` repository and tries to wipe it and reclone the repo. The delete process fails because Java can't handle a filename in `external/pugixml` that has Unicode (UTF-8) characters.

```
15:22:35 Started by upstream project "DualBootPatcher_Build" build number 128
15:22:35 originally caused by:
15:22:35  Started by upstream project "DualBootPatcher" build number 80
15:22:35  originally caused by:
15:22:35   Started by GitHub push by chenxiaolong
15:22:35   Started by GitHub push by chenxiaolong
15:22:35 [EnvInject] - Loading node environment variables.
15:22:35 Building remotely on Home1 in workspace /home/jenkins/workspace/DualBootPatcher_Build/target/win32-i686-mingw-w64-gcc
15:22:36 Cloning the remote Git repository
15:22:36 Cloning repository https://github.com/chenxiaolong/DualBootPatcher.git
15:22:36 ERROR: Failed to clean the workspace
15:22:38 java.io.IOException: java.lang.reflect.InvocationTargetException
15:22:38 	at hudson.Util.isSymlinkJava7(Util.java:377)
15:22:38 	at hudson.Util.isSymlink(Util.java:342)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:308)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:454)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
15:22:38 	at hudson.remoting.Request$2.run(Request.java:332)
15:22:38 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
15:22:38 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:22:38 	at java.lang.Thread.run(Thread.java:745)
15:22:38 Caused by: java.lang.reflect.InvocationTargetException
15:22:38 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
15:22:38 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:22:38 	at java.lang.reflect.Method.invoke(Method.java:498)
15:22:38 	at hudson.Util.isSymlinkJava7(Util.java:372)
15:22:38 	... 22 more
15:22:38 Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/jenkins/workspace/DualBootPatcher_Build/target/win32-i686-mingw-w64-gcc/DualBootPatcher/external/pugixml/tests/data/????????.xml
15:22:38 	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
15:22:38 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
15:22:38 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
15:22:38 	at java.io.File.toPath(File.java:2234)
15:22:38 	... 26 more
15:22:38 ERROR: Error cloning remote repo 'origin'
15:22:38 hudson.plugins.git.GitException: Failed to delete workspace
15:22:38 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:457)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
15:22:38 	at hudson.remoting.Request$2.run(Request.java:332)
15:22:38 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
15:22:38 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:22:38 	at java.lang.Thread.run(Thread.java:745)
15:22:38 	at ......remote call to Home1(Native Method)
15:22:38 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
15:22:38 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
15:22:38 	at hudson.remoting.Channel.call(Channel.java:781)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
15:22:38 	at sun.reflect.GeneratedMethodAccessor467.invoke(Unknown Source)
15:22:38 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:22:38 	at java.lang.reflect.Method.invoke(Method.java:606)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
15:22:38 	at com.sun.proxy.$Proxy63.execute(Unknown Source)
15:22:38 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1057)
15:22:38 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
15:22:38 	at hudson.scm.SCM.checkout(SCM.java:485)
15:22:38 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
15:22:38 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
15:22:38 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:22:38 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
15:22:38 	at hudson.model.Run.execute(Run.java:1738)
15:22:38 	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
15:22:38 	at hudson.model.ResourceController.execute(ResourceController.java:98)
15:22:38 	at hudson.model.Executor.run(Executor.java:410)
15:22:38 Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
15:22:38 	at hudson.Util.isSymlinkJava7(Util.java:377)
15:22:38 	at hudson.Util.isSymlink(Util.java:342)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:308)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at hudson.Util.deleteRecursive(Util.java:309)
15:22:38 	at hudson.Util.deleteContentsRecursive(Util.java:220)
15:22:38 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:454)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
15:22:38 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
15:22:38 	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
15:22:38 	at hudson.remoting.Request$2.run(Request.java:332)
15:22:38 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
15:22:38 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:22:38 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:22:38 	at java.lang.Thread.run(Thread.java:745)
15:22:38 Caused by: java.lang.reflect.InvocationTargetException
15:22:38 	at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
15:22:38 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:22:38 	at java.lang.reflect.Method.invoke(Method.java:498)
15:22:38 	at hudson.Util.isSymlinkJava7(Util.java:372)
15:22:38 	... 22 more
15:22:38 Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/jenkins/workspace/DualBootPatcher_Build/target/win32-i686-mingw-w64-gcc/DualBootPatcher/external/pugixml/tests/data/????????.xml
15:22:38 	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
15:22:38 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
15:22:38 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
15:22:38 	at java.io.File.toPath(File.java:2234)
15:22:38 	... 26 more
15:22:38 ERROR: null
15:22:38 Archiving artifacts
15:24:20 [xUnit] [INFO] - Starting to record.
15:24:20 [xUnit] [INFO] - Processing CTest-Version N/A (default)
15:24:21 [xUnit] [INFO] - [CTest-Version N/A (default)] - No test report file(s) were found with the pattern 'build/Testing/**/Test.xml' relative to '/home/jenkins/workspace/DualBootPatcher_Build/target/win32-i686-mingw-w64-gcc' for the testing framework 'CTest-Version N/A (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'CTest-Version N/A (default)'?
15:24:21 [xUnit] [WARNING] - No test reports found for the metric 'CTest' with the resolved pattern 'build/Testing/**/Test.xml'.
15:24:21 [xUnit] [INFO] - Skipping the metric tool processing.
15:24:21 [xUnit] [INFO] - There are errors when processing test results.
15:24:21 [xUnit] [INFO] - Skipping tests recording.
15:24:21 Finished: FAILURE
```

**Comment by chenxiaolong** [comment]
The issue was worked around by ensuring the slaves processes are run with `LANG=en_US.UTF-8` in the environment. Added `-Dfile.encoding=UTF-8` to the JVM's arguments did not work to remedy the issue.

**Comment by chenxiaolong** [comment]
Closing as we have a workaround.
